version: '3.8'
services:
  db:
    container_name: pg_container_edu_platform
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: education_platform
    ports:
      - "5432:5432"