server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    #    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://localhost:5432/education_platform?prepareThreshold=0
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #      dialect: org.hibernate.dialect.PostgreSQLDialect
      database-platform: org.hibernate.dialect.PostgreSQLDialect


